// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbWGXOB9WbW4UTb04D9OHXPChzGP6hH1s',
    appId: '1:595076892768:web:3caf135290110780371b05',
    messagingSenderId: '595076892768',
    projectId: 'skincare-app-6ebf6',
    authDomain: 'skincare-app-6ebf6.firebaseapp.com',
    storageBucket: 'skincare-app-6ebf6.firebasestorage.app',
    measurementId: 'G-WRMD8J7Z5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBii-hH7qsajul-szbC8MmSI1aWCcclyRo',
    appId: '1:595076892768:android:fb1acef053f0a2e2371b05',
    messagingSenderId: '595076892768',
    projectId: 'skincare-app-6ebf6',
    storageBucket: 'skincare-app-6ebf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-JhLBc9Si7MQwmwgYlKspFEH4LMMkOTw',
    appId: '1:595076892768:ios:6bdf20246d861a9a371b05',
    messagingSenderId: '595076892768',
    projectId: 'skincare-app-6ebf6',
    storageBucket: 'skincare-app-6ebf6.firebasestorage.app',
    iosBundleId: 'com.example.skincareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-JhLBc9Si7MQwmwgYlKspFEH4LMMkOTw',
    appId: '1:595076892768:ios:6bdf20246d861a9a371b05',
    messagingSenderId: '595076892768',
    projectId: 'skincare-app-6ebf6',
    storageBucket: 'skincare-app-6ebf6.firebasestorage.app',
    iosBundleId: 'com.example.skincareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbWGXOB9WbW4UTb04D9OHXPChzGP6hH1s',
    appId: '1:595076892768:web:fc370e9ce05d9dba371b05',
    messagingSenderId: '595076892768',
    projectId: 'skincare-app-6ebf6',
    authDomain: 'skincare-app-6ebf6.firebaseapp.com',
    storageBucket: 'skincare-app-6ebf6.firebasestorage.app',
    measurementId: 'G-7CPZK95NYQ',
  );
}
